default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: crime_development

test:
  <<: *default
  database: crime_test

production:
  <<: *default
  database: crime_production
